import React, { useState } from 'react';
import { X, Plus } from 'lucide-react';
import toast, { Toaster } from 'react-hot-toast';

const PlayerInputSidebar = ({ isOpen, onClose, onAddPlayer, players }) => {
  const [playerName, setPlayerName] = useState('');
  const [playerImage, setPlayerImage] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!playerName || !playerImage) {
      toast.error('Please fill in all fields');
      return;
    }

    const newPlayer = {
      "Player Name": playerName,
      "Total GOAT Points": 0,
      "image": playerImage,
      "Tier": "Got Next Tier",
      "Achievements": {
        "Win Championship as rookie": false,
        "Rookie Finals MVP": false,
        "Rookie Of The Year": false,
        "Most rookie Triple-Doubles": false,
        "Most rookie Blocks": false,
        "Most rookie Rebounds": false,
        "Most rookie Points": false,
        "Most rookie Steals": false,
        "Most rookie Assists": false,
        "Most rookie 3PM": false,
        "2nd most rookie Triple-Doubles": false,
        "2nd most rookie Blocks": false,
        "2nd most rookie Assists": false,
        "2nd most rookie Steals": false,
        "2nd most rookie 3PM": false,
        "2nd most rookie Points": false,
        "2nd most rookie Rebounds": false,
        "3rd most rookie Triple-Doubles": false,
        "3rd most rookie 3PM": false,
        "3rd most rookie Steals": false,
        "3rd most rookie Points": false,
        "3rd most rookie Rebounds": false,
        "3rd most rookie Assists": false,
        "3rd most rookie Blocks": false,
        "4th most rookie Blocks": false,
        "4th most rookie Rebounds": false,
        "4th most rookie Triple-Doubles": false,
        "4th most rookie Steals": false,
        "4th most rookie Assists": false,
        "4th most rookie 3PM": false,
        "4th most rookie Points": false,
        "5th most rookie Rebounds": false,
        "5th most rookie Assists": false,
        "5th most rookie Triple-Doubles": false,
        "5th most rookie 3PM": false,
        "5th most rookie Steals": false,
        "5th most rookie Blocks": false,
        "5th most rookie Points": false,
        "Rookie All-Star": false,
        "time All-Star": 0,
        "10x All-Star": false,
        "12 Championships": false,
        "7 Championships": false,
        "6 Championships": false,
        "5 Championships": false,
        "3-peat Championships": false,
        "2nd 3-peat": false,
        "6-0 in Finals": false,
        "Back-to-back Championships": false,
        "Championship with no 90+ OVR": 0,
        "Championship with 1 player 90+ OVR": 0,
        "Championship with 2 players 90+ OVR": 0,
        "Championship with 3+ players 90+ OVR": 0,
        "Championship as 7th/8th seed": 0,
        "WIN AN MVP": 0,
        "Back-to-back MVPs": false,
        "5 MVPs": false,
        "4 MVPs": false,
        "3-peat MVPs": false,
        "4 consecutive MVPs": false,
        "5 consecutive MVPs": false,
        "time DPOY": 0,
        "Back-to-back DPOYs": false,
        "5 DPOYs": false,
        "4 DPOYs": false,
        "3-peat DPOYs": false,
        "4 consecutive DPOYs": false,
        "5 consecutive DPOYs": false,
        "time 1st Team All-NBA": 0,
        "time 2nd Team All-NBA": 0,
        "time 3rd Team All-NBA": 0,
        "time 1st Team All-Defensive": 0,
        "time 2nd Team All-Defensive": 0,
        "Record 100 Points in game": false,
        "Record 55 Rebounds in game": false,
        "Record 14 3PM in game": false,
        "Record 30 Assists in game": false,
        "Record 17 Blocks in game": false,
        "Record 11 Steals in game": false,
        "2nd most Points in game": false,
        "2nd most Rebounds in game": false,
        "2nd most 3PM in game": false,
        "2nd most Assists in game": false,
        "2nd most Blocks in game": false,
        "2nd most Steals in game": false,
        "3rd most Points in game": false,
        "3rd most Rebounds in game": false,
        "3rd most 3PM in game": false,
        "3rd most Assists in game": false,
        "3rd most Blocks in game": false,
        "3rd most Steals in game": false,
        "4th most Points in game": false,
        "4th most Rebounds in game": false,
        "4th most 3PM in game": false,
        "4th most Assists in game": false,
        "4th most Blocks in game": false,
        "4th most Steals in game": false,
        "5th most Points in game": false,
        "5th most Rebounds in game": false,
        "5th most 3PM in game": false,
        "5th most Assists in game": false,
        "5th most Blocks in game": false,
        "5th most Steals in game": false,
        "Record playoff Points": false,
        "Record playoff Blocks": false,
        "Record playoff Rebounds": false,
        "Record playoff Assists": false,
        "Record playoff Steals": false,
        "Record playoff 3PM": false,
        "2nd most playoff Points": false,
        "2nd most playoff Blocks": false,
        "2nd most playoff Rebounds": false,
        "2nd most playoff Assists": false,
        "2nd most playoff Steals": false,
        "2nd most playoff 3PM": false,
        "3rd most playoff Points": false,
        "3rd most playoff Blocks": false,
        "3rd most playoff Rebounds": false,
        "3rd most playoff Assists": false,
        "3rd most playoff Steals": false,
        "3rd most playoff 3PM": false,
        "4th most playoff Points": false,
        "4th most playoff Blocks": false,
        "4th most playoff Rebounds": false,
        "4th most playoff Assists": false,
        "4th most playoff Steals": false,
        "4th most playoff 3PM": false,
        "5th most playoff Points": false,
        "5th most playoff Blocks": false,
        "5th most playoff Rebounds": false,
        "5th most playoff Assists": false,
        "5th most playoff Steals": false,
        "5th most playoff 3PM": false,
        "Career Points record": false,
        "Career Assists record": false,
        "Career Rebounds record": false,
        "Career Blocks record": false,
        "Career Steals record": false,
        "Career 3PM record": false,
        "Career Triple-Doubles record": false,
        "Career 40-Point games record": false,
        "Career 50-Point games record": false,
        "2nd most Career Points": false,
        "2nd most Career Assists": false,
        "2nd most Career Rebounds": false,
        "2nd most Career Blocks": false,
        "2nd most Career Steals": false,
        "2nd most Career 3PM": false,
        "2nd most Career Triple-Doubles": false,
        "2nd most Career 40-Point games": false,
        "2nd most Career 50-Point games": false,
        "3rd most Career Points": false,
        "3rd most Career Assists": false,
        "3rd most Career Rebounds": false,
        "3rd most Career Blocks": false,
        "3rd most Career Steals": false,
        "3rd most Career 3PM": false,
        "3rd most Career Triple-Doubles": false,
        "3rd most Career 40-Point games": false,
        "3rd most Career 50-Point games": false,
        "4th most Career Points": false,
        "4th most Career Assists": false,
        "4th most Career Rebounds": false,
        "4th most Career Blocks": false,
        "4th most Career Steals": false,
        "4th most Career 3PM": false,
        "4th most Career Triple-Doubles": false,
        "4th most Career 40-Point games": false,
        "4th most Career 50-Point games": false,
        "5th most Career Points": false,
        "5th most Career Assists": false,
        "5th most Career Rebounds": false,
        "5th most Career Blocks": false,
        "5th most Career Steals": false,
        "5th most Career 3PM": false,
        "5th most Career Triple-Doubles": false,
        "5th most Career 40-Point games": false,
        "5th most Career 50-Point games": false,
        "Top 10 Career Points": false,
        "Top 10 Career Assists": false,
        "Top 10 Career Rebounds": false,
        "Top 10 Career Blocks": false,
        "Top 10 Career Steals": false,
        "Top 10 Career 3PM": false,
        "Top 10 Career Triple-Doubles": false,
        "Top 50 Career Points": false,
        "Top 50 Career Assists": false,
        "Top 50 Career Rebounds": false,
        "Top 50 Career Blocks": false,
        "Top 50 Career Steals": false,
        "Top 50 Career 3PM": false,
        "Top 50 Career Triple-Doubles": false,
        "Top 100 Career Points": false,
        "Top 100 Career Assists": false,
        "Top 100 Career Rebounds": false,
        "Top 100 Career Blocks": false,
        "Top 100 Career Steals": false,
        "Top 100 Career 3PM": false,
        "Top 100 Career Triple-Doubles": false,
        "Team Record Points in game": false,
        "Team Record Rebounds in game": false,
        "Team Record Blocks in game": false,
        "Team Record Steals in game": false,
        "Team Record 3PM in game": false,
        "Team Record Assists in game": false,
        "2nd most team playoff Points": false,
        "2nd most team playoff Rebounds": false,
        "2nd most team playoff Blocks": false,
        "2nd most team playoff Steals": false,
        "2nd most team playoff 3PM": false,
        "2nd most team playoff Assists": false,
        "3rd most team playoff Points": false,
        "3rd most team playoff Rebounds": false,
        "3rd most team playoff Blocks": false,
        "3rd most team playoff Steals": false,
        "3rd most team playoff 3PM": false,
        "3rd most team playoff Assists": false,
        "4th most team playoff Points": false,
        "4th most team playoff Rebounds": false,
        "4th most team playoff Blocks": false,
        "4th most team playoff Steals": false,
        "4th most team playoff 3PM": false,
        "4th most team playoff Assists": false,
        "5th most team playoff Points": false,
        "5th most team playoff Rebounds": false,
        "5th most team playoff Blocks": false,
        "5th most team playoff Steals": false,
        "5th most team playoff 3PM": false,
        "5th most team playoff Assists": false,
        "Quadruple-double": false,
        "Quintuple-double": false,
        "Triple-double": false,
        "1,000 Points": false,
        "1,000 Rebounds": false,
        "1,000 Assists": false,
        "1,000 Blocks": false,
        "1,000 Steals": false,
        "1,000 3PM": false,
        "1,000 Triple-Doubles": false,
        "60 Points and Triple-Double": false,
        "60-20-10 Triple-Double": false,
        "20-20-20 Triple-Double": false,
        "40+ Points in game": false,
        "50+ Points in game": false,
        "60 Points in game": false,
        "71+ Points in game": false,
        "30+ Points with 90% FG%": false,
        "27+ Rebounds in game": false,
        "15+ Rebounds in game": false,
        "12+ Rebounds in game": false,
        "6+ Blocks in game": false,
        "5+ Blocks in game": false,
        "4+ Blocks in game": false,
        "5+ Steals in game": false,
        "3+ Steals in game": false,
        "10+ Assists in game": false,
        "14+ Assists in game": false,
        "15+ Assists in game": false,
        "5+ 3PM in game": false,
        "6+ 3PM in game": false,
        "4+ 3PM in game": false,
        "10 FGM without miss": false,
        "100 Points": false,
        "100 Rebounds": false,
        "100 Assists": false,
        "100 Blocks": false,
        "100 Steals": false,
        "100 3PM": false,
        "100 Triple-Doubles": false,
        "Fastest to 30,000 Points": false,
        "Fastest to 20,000 Points": false,
        "Fastest to 10,000 Points": false,
        "Fastest to 5,000 Points": false,
        "Fastest to 3,000 Blocks": false,
        "Fastest to 2,000 Points": false,
        "Fastest to 1,000 Blocks": false,
        "Avg 20/10/5 for 5+ seasons": false,
        "5,000 Points & 1,500 Assists in 200 games": false,
        "New playoff high Assists": false,
        "New playoff high Blocks": false,
        "New playoff high Steals": false,
        "New playoff high Points": false,
        "New playoff high 3PM": false,
        "New playoff high Rebounds": false,
        "Undefeated playoff run": false,
        "Reverse sweep in playoffs": false,
        "Reverse sweep top seed": false,
        "20 game win streak": false,
        "10 game win streak": false,
        "5 game win streak": false,
        "Player of the Month": false,
        "Sweep top seed in playoffs": false,
        "Sweep playoff series": false,
        "Sweep season series": false,
        "Beat previous season's champions": false,
        "Better rookie debut than LeBron": false,
        "Better rookie debut than MJ": false,
        "Eliminate former team in playoffs": false,
        "Eliminate top seed in playoffs": false,
        "Eliminate rival team in playoffs": false,
        "Win Finals rematch": false,
        "Clinching playoffs": false,
        "Clinch playoffs in finale": false,
        "League Leader in multiple stats": false,
        "First triple-double": false,
        "Triple-double in playoffs": false,
        "Quadruple-double in playoffs": false,
        "Double-double with no turnovers in playoffs": false,
        "100% FG in playoffs (min 10 shots)": false,
        "759+ points in single playoff run": false,
        "Top Kobe's 81 Points": false,
        "Goals vs bottom 5 team": false,
        "Goals vs leader in Points": false,
        "Goals vs leader in Rebounds": false,
        "Goals vs leader in Assists": false,
        "Goals vs leader in 3PM": false,
        "Goals vs leader in Steals": false,
        "Goals vs 85+ OVR player": false,
        "Goals vs top MVP candidate": false,
        "Goals vs top ROTY candidate": false,
        "Goals vs Rookie of the Month": false,
        "Goals vs team on hot streak": false,
        "Goals vs player on win streak": false,
        "Goals vs 2nd best team": false,
        "Goals vs top conference team": false,
        "Goals vs top league team": false,
        "Goals vs last season's MVP": false,
        "Goals vs last season's ROTY": false,
        "Goals vs last season's finalists": false,
        "Goals vs tied team in league": false,
        "Goals vs tied team in conference": false,
        "Goals in first game vs star": false,
        "Goals in second game vs star": false,
        "Goals in Truck anniversary game": false,
        "Goals at start of road trip": false,
        "Goals after All-Star announcement": false,
        "Goals in first game after trade deadline": false,
        "Goals in last game of season": false,
        "Goals to go 1-2 in season series": false,
        "Goals to go 2-2 in season series": false,
        "Come back from 20+ point deficit": false,
        "Beat rival team": false,
        "Break 20 game loss streak": false,
        "Break 10 game loss streak": false,
        "Break 5 game loss streak": false,
        "Clutch shot to win playoff game": false,
        "Clutch shot to send game to OT": false,
        "Win playoff game in OT": false,
        "Win All-Star Game": false,
        "Back-to-back 30+ point double-doubles": false
      },
      "rank": players.length + 1
    };

    onAddPlayer(newPlayer);
    setPlayerName('');
    setPlayerImage('');
    toast.success('Player added successfully');
  };

  return (
    <div className={`player-input-sidebar ${isOpen ? 'open' : ''}`}>
      <Toaster position="top-right" />
      <button className="close-btn" onClick={onClose}><X size={24} /></button>
      <div className="sidebar-content">
        <h2>Add New Player</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="playerName">Player Name</label>
            <input
              type="text"
              id="playerName"
              value={playerName}
              onChange={(e) => setPlayerName(e.target.value)}
              placeholder="Enter player name"
            />
          </div>
          <div className="form-group">
            <label htmlFor="playerImage">Player Image URL</label>
            <input
              type="text"
              id="playerImage"
              value={playerImage}
              onChange={(e) => setPlayerImage(e.target.value)}
              placeholder="Enter image URL"
            />
          </div>
          <button type="submit" className="submit-btn">
            <Plus size={18} />
            Add Player
          </button>
        </form>
      </div>
    </div>
  );
};

export default PlayerInputSidebar;